image:
  name: willhallonline/ansible:2.9-centos-8

cache:
  untracked: true
  policy: pull-push

stages:
  - test
  - start

variables:
  PLAYBOOK: cron_users_edit.yml
  ANSIBLE_HOST_KEY_CHECKING: "False"  
  GIT_STRATEGY: clone
  
test_playbook:
  stage: test
  script:
    - rm -rf roles
    - ansible-galaxy install -r requirements.yml --roles-path roles
    - ansible --version
    - echo "================= Тест1 =================="
    - ansible-lint -p ${PLAYBOOK}


start_playbook:
  stage: start    
  script:
    - git clone git@srv-glory.eurostil.ru:ansible/inventory.git
    - echo 'QXyU27Xw3HTkcnk6YR' > .ansible_vault_pass
    - rm -rf roles
    - ansible-galaxy install -r requirements.yml --roles-path roles
    - ansible-playbook ${PLAYBOOK} -i inventory/ --vault-password-file=.ansible_vault_pass --diff
  when: manual
